Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
  0%|          | 0.00/97.8M [00:00<?, ?B/s]  0%|          | 400k/97.8M [00:00<00:25, 4.04MB/s]  1%|1         | 1.23M/97.8M [00:00<00:16, 6.00MB/s]  3%|2         | 2.58M/97.8M [00:00<00:12, 8.10MB/s]  4%|4         | 4.12M/97.8M [00:00<00:10, 9.59MB/s]  6%|6         | 5.94M/97.8M [00:00<00:08, 11.1MB/s]  8%|8         | 8.02M/97.8M [00:00<00:07, 12.7MB/s] 11%|#         | 10.4M/97.8M [00:00<00:06, 14.5MB/s] 13%|#3        | 13.2M/97.8M [00:01<00:05, 16.5MB/s] 17%|#6        | 16.2M/97.8M [00:01<00:04, 20.5MB/s] 19%|#9        | 18.7M/97.8M [00:01<00:04, 20.1MB/s] 22%|##2       | 21.5M/97.8M [00:01<00:03, 22.7MB/s] 26%|##5       | 25.3M/97.8M [00:01<00:03, 25.3MB/s] 29%|##9       | 28.7M/97.8M [00:01<00:02, 27.9MB/s] 33%|###3      | 32.6M/97.8M [00:01<00:02, 31.7MB/s] 37%|###7      | 36.5M/97.8M [00:01<00:01, 34.0MB/s] 43%|####2     | 41.6M/97.8M [00:01<00:01, 38.1MB/s] 47%|####7     | 46.3M/97.8M [00:02<00:01, 41.2MB/s] 53%|#####2    | 51.8M/97.8M [00:02<00:01, 43.9MB/s] 59%|#####8    | 57.3M/97.8M [00:02<00:00, 47.7MB/s] 66%|######5   | 64.1M/97.8M [00:02<00:00, 54.5MB/s] 74%|#######3  | 71.9M/97.8M [00:02<00:00, 62.6MB/s] 82%|########1 | 79.9M/97.8M [00:02<00:00, 65.3MB/s] 91%|#########1| 89.0M/97.8M [00:02<00:00, 73.9MB/s]100%|##########| 97.8M/97.8M [00:02<00:00, 37.2MB/s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./tri_loss/dataset/Prefetcher.py", line 107, in enqueue
    element = self.get_element(ptr - 1)
  File "./tri_loss/dataset/TrainSet.py", line 55, in get_sample
    for name in im_names]
  File "./tri_loss/dataset/TrainSet.py", line 55, in <listcomp>
    for name in im_names]
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 5] Input/output error: "/content/drive/MyDrive/Triplet Loss/person-reid-triplet-loss-baseline/market1501/images/b'00001420_0005_00000001.jpg'"

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./tri_loss/dataset/Prefetcher.py", line 107, in enqueue
    element = self.get_element(ptr - 1)
  File "./tri_loss/dataset/TrainSet.py", line 55, in get_sample
    for name in im_names]
  File "./tri_loss/dataset/TrainSet.py", line 55, in <listcomp>
    for name in im_names]
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 5] Input/output error: "/content/drive/MyDrive/Triplet Loss/person-reid-triplet-loss-baseline/market1501/images/b'00001470_0006_00000001.jpg'"

Traceback (most recent call last):
  File "/usr/lib/python3.7/queue.py", line 170, in get
    self.not_empty.wait()
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script/experiment/train.py", line 558, in <module>
    main()
  File "script/experiment/train.py", line 446, in main
    ims, im_names, labels, mirrored, epoch_done = train_set.next_batch()
  File "./tri_loss/dataset/TrainSet.py", line 73, in next_batch
    samples, self.epoch_done = self.prefetcher.next_batch()
  File "./tri_loss/dataset/Prefetcher.py", line 181, in next_batch
    sample = self.enqueuer.queue1.get()
  File "/usr/lib/python3.7/queue.py", line 182, in get
    return item
  File "/usr/lib/python3.7/threading.py", line 243, in __exit__
    def __exit__(self, *args):
KeyboardInterrupt
